title: Learning GitHub Pages of [My GitHub](https://github.com/mujibluth)
author: Abdul Mujiburrohman Luthfi
email: abdulmujiburrohman.2019@student.uny.ac.id
description: > # this means to ignore newlines until "baseurl:"
  I built this GitHub Pages with the aim of completing my coursework task ğŸ“ğŸ“
  and at the same time deepening my knowledge ğŸ‘¨â€ğŸ“ of Workflows from GitHub Pages. Happy Learning ğŸ¥³

# social links
twitter_username: mujibluth # DO NOT include the @ character, or else the build will fail!
github_username:  mujibluth # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
